config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
                  path("", include("get_some_food.foodlist.urls", namespace="foodlist")),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("get_some_food.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

get_some_food/foodlist/urls.py
from django.urls import path

from get_some_food.foodlist.views import (
    ToBuyListView,
    PurchaseHistoryView,
    MyProductsView,
    PurchaseAjaxView,
    EditProductView,
    DeleteProductView,
    AddToBuyItemView,
    add_product_to_shopping_list,
    AddProductItemView,
    EditToBuyView,
    delete_to_buy_view,
    product_edit_popup,
    product_create_popup,
    category_edit_popup,
    category_create_popup,
)

app_name = "foodlist"

urlpatterns = [
    path("", ToBuyListView.as_view(), name="list"),
    path("products/", MyProductsView.as_view(), name="products"),
    path("history/", PurchaseHistoryView.as_view(), name="history"),
    path("purchase/", PurchaseAjaxView.as_view(), name="purchase"),
    path("products/edit/<int:pk>/", EditProductView.as_view(), name="edit_product"),
    path("products/delete/<int:pk>/", DeleteProductView.as_view(), name="delete_product"),

    path("product/<int:pk>/edit/", product_edit_popup, name="product_edit_popup"),
    path("product/create/", product_create_popup, name="product_create_popup"),

    path("category/<int:pk>/edit/", category_edit_popup, name="category_edit_popup"),
    path("category/create/", category_create_popup, name="category_create_popup"),

    path("tobuy/edit/<int:pk>/", EditToBuyView.as_view(), name="edit_tobuy"),
    path("tobuy/delete/<int:pk>/", delete_to_buy_view, name="delete_tobuy"),

    path("add-shopping-item/", AddToBuyItemView.as_view(), name="add_shopping_item"),
    path("add-product-to-list/<int:pk>/", add_product_to_shopping_list, name="add_product_to_shopping_list"),
    path("add-product-item/", AddProductItemView.as_view(), name="add_product_item"),
]

get_some_food/users/urls.py
from django.urls import path

from get_some_food.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

get_some_food/foodlist/models.py
from categories.models import Category
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Unit(models.Model):
    '''Units of measurement'''
    short_name = models.CharField(max_length=30)
    long_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.long_name} ({self.short_name})'


class Product(models.Model):
    name = models.CharField(max_length=255)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # срок годности
    shelf_life = models.DurationField(null=True, blank=True)
    # количество продукта, при котором нужно предупреждать о необходимости купить новый
    warn_amount = models.FloatField(default=1.0)
    # Для яиц - 10
    default_amount = models.FloatField(default=1.0)

    def __str__(self):
        return f'{self.name} ({self.unit.short_name})'


class ShoppingList(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_with = models.ManyToManyField(User, related_name='shopping_lists', blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.creation_date.strftime("%d-%m-%Y %H:%M")} {self.owner.username}'


class ShoppingListItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.FloatField(default=1.0)
    comment = models.TextField(blank=True)
    due_date = models.DateField(null=True, blank=True)
    shopping_list = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    purchased = models.BooleanField(default=False)
    display = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.product}: {self.amount} {self.product.unit.short_name}. {self.comment}'

    def save(self, *args, **kwargs):
        if self.amount < 0:
            self.amount = 0
        super().save(*args, **kwargs)


class Purchase(models.Model):
    item = models.ForeignKey(ShoppingListItem, on_delete=models.CASCADE)
    buy_date = models.DateField(auto_now_add=True)
    expiry_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.buy_date.strftime("%d-%m-%Y %H:%M")} {self.item}'


class ProductList(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_with = models.ManyToManyField(User, related_name='product_lists', blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.creation_date.strftime("%d-%m-%Y %H:%M")} {self.owner.username}'


class ProductItem(models.Model):
    product_list = models.ForeignKey(ProductList, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.FloatField(default=0.0)
    in_shopping_list = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.product} {self.amount} {self.product.unit.short_name}'

    def save(self, *args, **kwargs):
        if self.amount < 0:
            self.amount = 0
        super().save(*args, **kwargs)

get_some_food/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }
        labels = {
            'username': _('Name of the user'),
            'password': _('User password'),
            'email': _('User email'),
            'avatar': _('User avatar')
        }

get_some_food/foodlist/views.py
import datetime

from categories.models import Category
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, OuterRef, Subquery
from django.db.models.functions import ExtractDay, Coalesce
from django.http import HttpResponseRedirect
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, View, UpdateView, DeleteView, CreateView

from .forms import AddShoppingItemForm, AddProductItemForm, ProductForm, CategoryForm, EditShoppingItemForm
from .models import ShoppingListItem, Purchase, ProductItem, ProductList, Product, ShoppingList


class ToBuyListView(TemplateView):
    template_name = "pages/tobuy.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            shopping_list, _ = ShoppingList.objects.get_or_create(owner=self.request.user)
            context['items'] = ShoppingListItem.objects.filter(shopping_list=shopping_list, display=True).order_by(
                'purchased', 'due_date', '-creation_date')
        return context


class PurchaseAjaxView(View, LoginRequiredMixin):
    def post(self, request, *args, **kwargs):
        context = {'success': False}
        product_list, _ = ProductList.objects.get_or_create(owner=self.request.user)
        if self.request.is_ajax():
            item_id_str = self.request.POST.get("item_id")
            item = get_object_or_404(ShoppingListItem, pk=int(item_id_str[5:]))
            item.purchased = not item.purchased
            item.save()
            purchases = Purchase.objects.filter(item=item)
            if purchases.exists():
                purchase = purchases[0]
                product_item = ProductItem.objects.get(product=purchase.item.product, product_list=product_list)
                product_item.amount -= purchase.item.amount
                product_item.in_shopping_list = True
                product_item.save()
                purchase.delete()

                context['created'] = False
            else:
                purchase = Purchase(item=item)
                purchase.save()

                product_items = ProductItem.objects.filter(product=purchase.item.product, product_list=product_list)
                if product_items:
                    product_item = product_items[0]
                    product_item.amount += purchase.item.amount
                else:
                    product_item = ProductItem(product=purchase.item.product, amount=purchase.item.amount,
                                               product_list=product_list)

                product_item.in_shopping_list = False
                product_item.save()
                context['created'] = True
            context['success'] = True
        return JsonResponse(context)


class PurchaseHistoryView(ListView):
    model = Purchase
    template_name = "pages/history.html"
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_authenticated:
            shopping_list, _ = ShoppingList.objects.get_or_create(owner=self.request.user)
            return Purchase.objects.filter(item__shopping_list=shopping_list).order_by('-buy_date')

        return Purchase.objects.none()


class MyProductsView(ListView):
    model = ProductItem
    template_name = "pages/products.html"
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_authenticated:
            product_list, _ = ProductList.objects.get_or_create(owner=self.request.user)
            purchase_date = Purchase.objects.filter(item__product=OuterRef('product')).order_by('-buy_date')

            queryset = ProductItem.objects.filter(product_list=product_list).annotate(
                last_purchased_days=
                ExtractDay(datetime.datetime.today() - Coalesce(Subquery(purchase_date.values('buy_date')[:1]),
                                                                datetime.datetime.today()))
            ).annotate(
                amount_to_warn=F('amount') - F('product__warn_amount')
            ).order_by('-last_purchased_days', 'amount_to_warn')
            return queryset
        return ProductItem.objects.none()


class EditProductView(UpdateView, LoginRequiredMixin):
    model = ProductItem
    template_name = "product_edit.html"
    fields = ["amount"]
    success_url = '/products/'


class DeleteProductView(DeleteView, LoginRequiredMixin):
    model = ProductItem
    success_url = '/products/'


class AddToBuyItemView(CreateView, LoginRequiredMixin):
    template_name = 'add_tobuy_item.html'
    form_class = AddShoppingItemForm
    success_url = '/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.shopping_list, _ = ShoppingList.objects.get_or_create(owner=self.request.user)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


@login_required
def add_product_to_shopping_list(request, pk):
    shopping_list, _ = ShoppingList.objects.get_or_create(owner=request.user)
    product_item = ProductItem.objects.get(pk=pk)
    shopping_item = ShoppingListItem(shopping_list=shopping_list, product=product_item.product,
                                     amount=product_item.product.default_amount)
    product_item.in_shopping_list = True
    product_item.save()
    shopping_item.save()
    return redirect('/products/')


class AddProductItemView(CreateView, LoginRequiredMixin):
    model = ProductItem
    template_name = 'add_product_item.html'
    success_url = '/products/'
    form_class = AddProductItemForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.product_list = self.product_list
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.product_list, _ = ProductList.objects.get_or_create(owner=self.request.user)
        kwargs['product_list'] = self.product_list
        return kwargs


class EditToBuyView(UpdateView, LoginRequiredMixin):
    model = ShoppingListItem
    template_name = "tobuy_edit.html"
    form_class = EditShoppingItemForm
    success_url = '/'


@login_required
def delete_to_buy_view(request, pk):
    item = get_object_or_404(ShoppingListItem, pk=pk)
    item.display = False
    item.save()
    return redirect('/')


@login_required
def product_create_popup(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        ## Change the value of the "#id_product". This is the element id in the form
        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_product");</script>' % (instance.pk, instance))

    return render(request, "product_form.html", {"form": form})


@login_required
def product_edit_popup(request, pk=None):
    instance = get_object_or_404(Product, pk=pk)
    form = ProductForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save()
        ## Change the value of the "#id_product". This is the element id in the form

        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_product");</script>' % (instance.pk, instance))

    return render(request, "product_form.html", {"form": form})


@login_required
def category_create_popup(request):
    form = CategoryForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        ## Change the value of the "#id_category". This is the element id in the form
        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_category");</script>' % (instance.pk, instance))

    return render(request, "category_form.html", {"form": form})


@login_required
def category_edit_popup(request, pk=None):
    instance = get_object_or_404(Category, pk=pk)
    form = CategoryForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save()

        ## Change the value of the "#id_category". This is the element id in the form

        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_category");</script>' % (instance.pk, instance))

    return render(request, "category_form.html", {"form": form})

get_some_food/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

get_some_food/templates/add_product_item.html
{% load crispy_forms_tags %}
{# Add product item form #}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Add product item</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form id="add_product_item_form" method="post" action="">
      <div class="modal-body">
        {% csrf_token %}

        {{ form.product.label_tag }}

        <div class="d-flex flex-row justify-content-start mb-1">
          {{ form.product }}
          <a href="#" id="edit_product" class="text-muted btn-link" data-mdb-toggle="tooltip" title="Edit product"><i
                  class="fas fa-pencil-alt me-3"></i></a>
          <a href="{% url 'foodlist:product_create_popup' %}" onclick="return showAddPopup(this);" class="text-muted"
             data-mdb-toggle="tooltip" title="Add product"><i class="fas fa-plus-circle"></i></a>
        </div>
        {{ form.amount|as_crispy_field }}
      </div>
      <div class="modal-footer">
        <input type="submit" value="Apply" class="btn btn-primary"/>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </form>
  </div>
</div>

get_some_food/templates/add_tobuy_item.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Add product to the list</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form id="add_item_form" method="post" action="">
      <div class="modal-body">
        {% csrf_token %}
        {{ form.product.label_tag }}

        <div class="d-flex flex-row justify-content-start mb-1">
          {{ form.product }}
          <a href="#" id="edit_product" class="text-muted btn-link" data-mdb-toggle="tooltip" title="Edit product"><i
                  class="fas fa-pencil-alt me-3"></i></a>
          <a href="{% url 'foodlist:product_create_popup' %}" onclick="return showAddPopup(this);" class="text-muted"
             data-mdb-toggle="tooltip" title="Add product"><i class="fas fa-plus-circle"></i></a>
        </div>
        {{ form.amount|as_crispy_field }}
        {{ form.due_date|as_crispy_field }}
        {{ form.comment|as_crispy_field }}
      </div>
      <div class="modal-footer">
        <input type="submit" id="add_item_submit" class="btn btn-primary" value="Add"/>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </form>
  </div>
</div>

get_some_food/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Get Some Food{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Smart food shopping list">
  <meta name="author" content="Aleksandr Sergeenko">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    {% comment %}<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">{% endcomment %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'foodlist:list' %}"><img src="{% static 'images/logo.png' %}"></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'foodlist:list' %}">{% translate "To Buy" %}<span
                  class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'foodlist:products' %}">{% translate "My products" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'foodlist:history' %}">{% translate "History" %}</a>
        </li>
      </ul>
      <ul class="navbar-nav justify-content-end">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Log out" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username %}">
              <img src="{{ request.user.avatar.url }}" width="32" height="32">
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {# Script tags with only code, no src (defer by default) #}
{% endblock inline_javascript %}
<script>
  $(document).ready(function () {
    {% block jquery %}
    {% endblock jquery %}
  });
</script>
</body>
</html>

get_some_food/templates/product_list_item.html
<div class="row my-1 {% if item.in_shopping_list %}item-in-list{% elif item.amount_to_warn < 0 and not item.in_shopping_list %}item-warn{% endif %}">
  <div class="col-md-6">
    <p class="lead fw-normal mb-0"><strong>{{ item.product.name }}</strong></p>
  </div>
  <div class="col-md-2">
    <p class="mb-0">{{ item.amount|floatformat:"-1" }} {{ item.product.unit.short_name }}</p>
  </div>
  <div class="col-md-2">
    <p class="mb-0">
      {% if item.last_purchased_days >= 0 %}
        {% if item.last_purchased_days == 0 %}сегодня
          {% else %}{{ item.last_purchased_days }}
          {% if item.last_purchased_days == 1 %}день
          {% elif item.last_purchesed_days >= 2 and item.last_purchased_days <= 4 %}дня
          {% else %}дней
          {% endif %}
          назад
        {% endif %}
      {% endif %}
    </p>
  </div>
  <div class="col-md-2">
    <div class="d-flex flex-row justify-content-start mb-1">
      <a href="#" data-title="{{ item.product.name }}" data-form="{% url 'foodlist:edit_product' pk=item.pk %}"
         class="text-muted edit" data-mdb-toggle="tooltip" title="Edit product"><i
              class="fas fa-pencil-alt me-3"></i></a>
      <a href="#" data-title="{{ item.product.name }}" data-form="{% url 'foodlist:delete_product' pk=item.pk %}"
         class="text-muted del" data-mdb-toggle="tooltip" title="Delete product"><i
              class="fas fa-trash-alt me-3"></i></a>
      {% if not item.in_shopping_list %}
        <a href="{% url 'foodlist:add_product_to_shopping_list' pk=item.pk %}" class="text-muted"
           data-mdb-toggle="tooltip" title="Add product to shopping list"><i
                class="fas fa-plus-circle"></i></a>{% endif %}

    </div>
  </div>
</div>

get_some_food/templates/shopping_list_item.html
<div class="row my-1{% if item.purchased %} done{% endif %}">
  <div class="col-md-1">

    <input
            class="form-check-input"
            type="checkbox" {% if item.purchased %}checked{% endif %}
            value=""
            id="item_{{ item.pk }}"
            aria-label="..."
    />

  </div>
  <div class="col-md-3">
    <p class="lead fw-normal mb-0">{{ item.product.name }}</p>
  </div>
  <div class="col-md-2">
    <p class="lead fs-6 mb-0">{{ item.amount|floatformat:"-1" }} {{ item.product.unit.short_name }}</p>
  </div>
  <div class="col-md-3">
    <p class="lead fs-6 mb-0">{{ item.comment }}</p>
  </div>
  <div class="col-md-2">
    {% if item.due_date %}
      <p class="lead fs-6 mb-0">{{ item.due_date|date:"d-m-Y" }}</p>
    {% endif %}
  </div>

  <div class="col-md-1">
    <div class="d-flex flex-row justify-content-end mb-1">
      <a href="#" data-title="{{ item.product.name }}" data-form="{% url 'foodlist:edit_tobuy' pk=item.pk %}"
         class="text-info edit" data-mdb-toggle="tooltip" title="Edit todo"><i class="fas fa-pencil-alt me-3"></i></a>
      <a href="#" data-title="{{ item.product.name }}" data-form="{% url 'foodlist:delete_tobuy' pk=item.pk %}"
         class="text-danger del" data-mdb-toggle="tooltip" title="Delete todo"><i class="fas fa-trash-alt"></i></a>
    </div>
  </div>
</div>